#!/bin/bash

echo 'echo "$1", $2....'
echo 'esse comando vai dizer e mostrar cada argumento individual, assim que eu chamar o script.'
echo 'exemplo:'
echo './doze.sh 2 4; supondo que o scritp doze.sh seja o somatório de dois numeros inteiros. e esses números foram passados pelo usuário: 2 e 4'
echo ' '
echo 'echo $*'
echo 'esse comando, vai mostrar todos os argumentos de linha de comando..'
echo 'exemplo:'
echo 'no meu caso, mostraria aqui: vazio, se eu chamar direto do bash'
echo ' '
echo 'echo $0'
echo 'vai mostrar todos os comandos executados naquele exato momento.'
echo 'exemplo:'
echo '> bash'
echo ' '
echo 'echo $!'
echo 'vai mostrar o número do último comando executado pelo usuário!'
echo 'exemplo:'
echo 'aqui no meu caso: >vazio.'
echo ' '
echo 'echo $HOME'
echo 'vai mostrar o caminho do diretório do usuário.'
echo 'exemplo:'
echo 'meu caso: >/home/panda'
echo ' '
echo 'echo $BASH'
echo 'vai mostrar qual o bash que o usuário usa no momento.'
echo 'exemplo:'
echo 'meu caso: >/usr/bin/bash'
echo ' '

